name: Build and publish pdf to Google Drive
on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile main.tex
        uses: dante-ev/latex-action@edge
        with:
          root_file: main.tex

      - name: Upload compiled artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled
          path: main.pdf

  publish_to_google_drive:
    runs-on: ubuntu-latest
    needs: build_latex
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Download artifact from previous job
        uses: actions/download-artifact@v4
        with:
          name: compiled
          path: ./

      - name: Rename PDF with commit hash
        run: mv main.pdf main-${{ github.sha }}.pdf

      - name: Verify file exists
        run: ls -la main-${{ github.sha }}.pdf

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Google Drive API dependencies
        run: |
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Upload to Google Drive
        run: |
          cat > upload_to_drive.py << 'EOF'
          import json
          import os
          from google.oauth2 import service_account
          from googleapiclient.discovery import build
          from googleapiclient.http import MediaFileUpload

          # Load credentials from environment
          creds_b64 = os.environ['GOOGLE_DRIVE_CREDENTIALS']
          folder_id = os.environ['GOOGLE_DRIVE_FOLDER_ID']
          filename = os.environ['FILENAME']

          # Decode credentials
          import base64
          creds_json = base64.b64decode(creds_b64).decode('utf-8')
          creds_info = json.loads(creds_json)

          # Create credentials object
          credentials = service_account.Credentials.from_service_account_info(
              creds_info, scopes=['https://www.googleapis.com/auth/drive.file']
          )

          # Build the service
          service = build('drive', 'v3', credentials=credentials)

          # Upload file
          file_metadata = {
              'name': filename,
              'parents': [folder_id]
          }

          media = MediaFileUpload(filename, mimetype='application/pdf')

          try:
              file = service.files().create(
                  body=file_metadata,
                  media_body=media,
                  fields='id'
              ).execute()
              print(f'File uploaded successfully. File ID: {file.get("id")}')
          except Exception as e:
              print(f'Error uploading file: {str(e)}')
              exit(1)
          EOF

          python upload_to_drive.py
        env:
          GOOGLE_DRIVE_CREDENTIALS: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          FILENAME: main-${{ github.sha }}.pdf
