name: Build and publish pdf to Google Drive
on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile main.tex
        uses: dante-ev/latex-action@edge
        with:
          root_file: main.tex

      - name: Upload compiled artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled
          path: main.pdf

  publish_to_google_drive:
    runs-on: ubuntu-latest
    needs: build_latex
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Download artifact from previous job
        uses: actions/download-artifact@v4
        with:
          name: compiled
          path: ./

      - name: Rename PDF with commit hash
        run: mv main.pdf main-${{ github.sha }}.pdf

      - name: Verify file exists
        run: ls -la main-${{ github.sha }}.pdf

      - name: Debug - Check folder ID length
        run: echo "Folder ID length:" $(echo "${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}" | wc -c)

      - name: Debug - Verify credentials format
        run: |
          echo "Checking if credentials contain required fields..."
          echo "${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}" | grep -q "client_email" && echo "✓ client_email found" || echo "✗ client_email missing"
          echo "${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}" | grep -q "private_key" && echo "✓ private_key found" || echo "✗ private_key missing"

      - name: Upload to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          filename: main-${{ github.sha }}.pdf
          folderId: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          name: main-${{ github.sha }}.pdf
          overwrite: "true"